version: 2
updates:
  - package-ecosystem: "npm" 
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
      include: "scope"
    assignees:
      - "matt-wigg"
    labels:
      - "dependencies"
      - "automated-pr"
    reviewers:
      - "matt-wigg"
